### ISSUE TITLE
Text Edits

### ISSUE THREAD

**Issue by jenniferspence** [rer145/dental-ta#21]
Under Current Scores, please
1. Capitalize "Permanent" and "Deciduous"
2. Replace "maxillary" and "mandibular" with "Maxilla" and "Mandible"
3. Use "Right" and "Left" instead of "R" and "L"

On Scoring page, please add "Dentition" after "Permanent" and "Deciduous"

**Comment by rer145** [comment]
This has been updated and will be included in the next release.
