### ISSUE TITLE
Website link

### ISSUE THREAD

**Issue by jenniferspence** [rer145/dental-ta#25]
Website link is to Penn State

**Comment by rer145** [comment]
Oops! Sorry about that.  Where should I make the link to go? Since this project involves a couple universities, should there be 2 links?

I'm thinking one to:  https://www.txstate.edu/anthropology/
And another to: https://anthropology.msu.edu/

**Comment by jenniferspence** [comment]
Please have the link go to https://tada.wp.txstate.edu/

I'll check to see if we want additional links. Thx
