### ISSUE TITLE
Headings

### ISSUE THREAD

**Issue by jenniferspence** [rer145/dental-ta#29]
Scoring Page: Delete the words “Crown”, “Root”, and “Apex” above the line drawings/X-rays (permanent and deciduous dentition). Under deciduous dentition, change “Deciduous” above line drawings/X-rays to “Root Resorption Stages”. Do not separate line drawing/X-ray images by crown/root/apex categories (e.g., Crc should be next to Ri).

**Comment by rer145** [comment]
Just want to clarify... for deciduous, you want the last 3 items (Res 1/4, Res 1/2, and Res 3/4) to be separated from the others, or is the following image correct?

![image](https://user-images.githubusercontent.com/874002/106374457-abc13980-6351-11eb-89ea-b5a7ad90bea4.png)

**Comment by jenniferspence** [comment]
Initially I asked that the last 3 images be separated but I think this image is clearer. So, please keep what you have here.

**Comment by rer145** [comment]
Fixed in version 0.1.4
